DROP TABLE IF EXISTS BOOKS,GENRES,AUTHORS,BOOKS_AUTHORS;

CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE AUTHORS
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIO VARCHAR(255)
);

CREATE TABLE BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE     VARCHAR(255),
    GENRE_ID  BIGINT REFERENCES GENRES (ID)
);

CREATE TABLE COMMENTS
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID  BIGINT REFERENCES BOOKS (ID) on delete cascade,
    NICKNAME VARCHAR(255),
    MESSAGE  VARCHAR(255)
);

CREATE TABLE BOOKS_AUTHORS
(
    BOOK_ID   BIGINT REFERENCES BOOKS (id) on delete cascade,
    AUTHOR_ID BIGINT REFERENCES AUTHORS (id),
    PRIMARY KEY (BOOK_ID, AUTHOR_ID)
);