#spring:
#  data:
#    mongodb:
#      port: 0
#      database: test

spring:
  data:
    mongodb:
#      port: 0
      database: test
  resources:
    static-locations: classpath:/static/
server:
  port: 8090

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog



#  .static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/ # Locations of static resources.