#spring:
#  data:
#    mongodb:
#      port: 0
#      database: test

spring:
  data:
    mongodb:
      database: test

mongock:
  #  runner-type: "ApplicationRunner" # default
  runnertype: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.changelog